# Generated by Django 5.2.4 on 2025-08-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('MX', 'Mexican'), ('AM', 'American'), ('PH', 'Filipino'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
